import Link from "next/link";
import { Grape, Map, Mountain, MountainSnow, PawPrint, Users, Waves } from "lucide-react";
import { destinationSlug } from "@/lib/destinations";
import SiteFooter from "@/components/SiteFooter";
import MainMenu from "@/components/MainMenu";

const mountain="https://images.unsplash.com/photo-1704304343233-492236e5f34b?auto=format&fit=crop&w=1400&q=85", lion="https://images.unsplash.com/photo-1649724264150-50dbfdc606c5?auto=format&fit=crop&w=900&q=85", vineyard="https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=85", coast="https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=85";
const whatsapp="https://wa.me/56935709244?text=Ol%C3%A1%2C%20quero%20solicitar%20um%20or%C3%A7amento%20de%20viagem";
const highlights=[{Icon:MountainSnow,title:"Viagens para a neve",text:"Aproveite os melhores centros de esqui com transporte confortável e seguro."},{Icon:PawPrint,title:"Parque Safari",text:"Viva uma experiência inesquecível no Parque Safari Chile."},{Icon:Grape,title:"Rotas do vinho",text:"Conheça vinícolas exclusivas com traslado e opções com ingresso incluído."},{Icon:Mountain,title:"Portillo e Laguna del Inca",text:"Paisagens únicas na cordilheira e a famosa Laguna del Inca."},{Icon:Waves,title:"Costa e litoral",text:"Conheça as melhores praias e cidades costeiras do Chile."},{Icon:Map,title:"Cajón del Maipo",text:"Natureza, aventura e relaxamento perto de Santiago."}];
const trips=[{title:"Snow Park Farellones",img:"https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=900&q=85"},{title:"Valle Nevado",img:mountain},{title:"El Colorado",img:"https://images.unsplash.com/photo-1529669851596-ba9a5549af95?auto=format&fit=crop&w=900&q=85"},{title:"La Parva",img:"https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=900&q=85"},{title:"Portillo & Laguna del Inca",img:mountain},{title:"Cajón del Maipo",img:mountain},{title:"Embalse del Yeso",img:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85"},{title:"Termas de Colina",img:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=85"},{title:"Viña Concha y Toro",img:vineyard},{title:"Viña Alyan",img:vineyard},{title:"Viña Vik",img:vineyard},{title:"Viña Santa Rita",img:vineyard},{title:"Viña del Mar & Valparaíso",img:coast},{title:"Algarrobo & Isla Negra",img:coast},{title:"Parque Safari",img:lion},{title:"Tours personalizados",display:"Passeios personalizados",img:mountain}];
function Brand(){return <><Link className="brand" href="/pt" aria-label="Rutas Confiables, início"><img className="brand-logo" src="/favicon.png" alt="Logo oficial da Rutas Confiables"/><span className="header-brand-tagline">Transporte de passageiros<br/>e passeios</span></Link><MainMenu locale="pt"/></>}

export default function PortugueseHome(){return <main>
  <section className="hero" id="inicio"><nav><Brand/><div className="nav-links"><a href="#experiencias">Passeios</a><a href="#reserva">Opções completas</a><Link className="language-link" href="/" hrefLang="es">ES</Link><a className="button light" href={whatsapp}>Solicitar orçamento <span>→</span></a></div></nav><div className="hero-content"><p className="eyebrow">Transporte privativo · Santiago do Chile</p><h1>Sua próxima rota<br/>começa aqui.</h1><p className="hero-copy">Descubra neve, vinhedos, litoral, montanhas e experiências únicas no Chile com um serviço confortável, seguro e personalizado.</p><div className="actions"><a className="button light" href="#experiencias">Ver destinos <span>→</span></a><a className="button ghost" href={whatsapp}>Solicitar orçamento <span>→</span></a></div></div><div className="trust"><span>◇ <b>Transporte seguro</b><small>e confiável</small></span><span>♡ <b>Conforto</b><small>em cada viagem</small></span><span>☆ <b>Experiências</b><small>inesquecíveis</small></span></div></section>
  <section className="section intro"><h2>Muito mais que transporte.</h2><div className="highlight-grid">{highlights.map(({Icon,title,text})=><article key={title}><Icon className="highlight-icon" strokeWidth={1.7}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section trips" id="experiencias"><h2>Escolha sua próxima experiência.</h2><div className="trip-grid">{trips.map(({title,display,img},i)=><Link href={`/pt/destinos/${destinationSlug(title)}`} className="trip" key={title} style={{backgroundImage:`linear-gradient(0deg, rgba(0,16,50,.88), rgba(0,16,50,.04) 75%), url(${img})`,backgroundPosition:`${i%4*11}% center`}}><span>{display||title}</span></Link>)}<article className="custom"><Users className="custom-icon"/><div><b>Não encontrou seu destino?</b><p>Criamos experiências sob medida para você e seu grupo.</p><a href={whatsapp}>Fale conosco →</a></div></article></div></section>
  <SiteFooter locale="pt"/>
  <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Solicitar orçamento pelo WhatsApp"><img src="/whatsapp.svg" alt=""/></a>
</main>}
