const mountain = "https://images.unsplash.com/photo-1704304343233-492236e5f34b?auto=format&fit=crop&w=1400&q=85";
const lion = "https://images.unsplash.com/photo-1649724264150-50dbfdc606c5?auto=format&fit=crop&w=900&q=85";
const vineyard = "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=85";
const coast = "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=85";
const highlights = [{Icon:MountainSnow,title:"Viajes a la nieve",text:"Disfruta los mejores centros de ski con transporte cómodo y seguro."},{Icon:PawPrint,title:"Parque Safari",text:"Vive una experiencia inolvidable en el Parque Safari Chile."},{Icon:Grape,title:"Rutas del vino",text:"Descubre viñedos exclusivos con traslados y opciones con entrada incluida."},{Icon:Mountain,title:"Portillo y Laguna del Inca",text:"Paisajes únicos en la cordillera y la famosa Laguna del Inca."},{Icon:Waves,title:"Costa y litoral",text:"Recorre las mejores playas y ciudades costeras de Chile."},{Icon:Map,title:"Cajón del Maipo",text:"Naturaleza, aventura y relajación a pocos kilómetros de Santiago."}];
const trips = [{title:"Snow Park Farellones",img:"https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=900&q=85",Icon:Snowflake},{title:"Valle Nevado",img:mountain,Icon:MountainSnow},{title:"El Colorado",img:"https://images.unsplash.com/photo-1529669851596-ba9a5549af95?auto=format&fit=crop&w=900&q=85",Icon:CableCar},{title:"La Parva",img:"https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=900&q=85",Icon:Mountain},{title:"Parque Safari",img:lion,Icon:PawPrint},{title:"Portillo & Laguna del Inca",img:mountain,Icon:MountainSnow},{title:"Viña Concha y Toro",img:vineyard,Icon:Grape},{title:"Viña Alyan",img:vineyard,Icon:Grape},{title:"Viña Vik",img:vineyard,Icon:Grape},{title:"Viña Santa Rita",img:vineyard,Icon:Grape},{title:"Viña del Mar & Valparaíso",img:coast,Icon:Waves},{title:"Algarrobo & Isla Negra",img:coast,Icon:Waves},{title:"Cajón del Maipo",img:mountain,Icon:Map},{title:"Embalse del Yeso",img:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85",Icon:Mountain},{title:"Termas de Colina",img:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=85",Icon:Waves},{title:"Tours personalizados",img:mountain,Icon:Compass}];
const whatsapp = "https://wa.me/56935709244?text=Hola%2C%20quiero%20cotizar%20un%20viaje";

function Brand(){return <a className="brand" href="#inicio" aria-label="Rutas Confiables, inicio"><img className="brand-logo" src="/favicon.png" alt="" aria-hidden="true"/><span className="brand-copy"><b>RUTAS<br/>CONFIABLES</b><small>TRANSPORTE & TOURS</small></span></a>}
export default function Home(){return <main>
  <section className="hero" id="inicio"><nav><Brand/><div className="nav-links"><a href="#experiencias">Tours</a><a href="#reserva">Opciones completas</a><a className="button light" href={whatsapp}>Cotizar viaje <span>→</span></a></div></nav><div className="hero-content"><p className="eyebrow">Transporte privado · Santiago de Chile</p><h1>Tu próxima ruta<br/>comienza aquí.</h1><p className="hero-copy">Descubre la nieve, viñedos, costa, montaña y experiencias únicas de Chile con un servicio cómodo, seguro y personalizado.</p><div className="actions"><a className="button light" href="#experiencias">Ver destinos <span>→</span></a><a className="button ghost" href={whatsapp}>Solicitar cotización <span>→</span></a></div></div><div className="trust"><span>◇ <b>Transporte seguro</b><small>y confiable</small></span><span>♡ <b>Comodidad</b><small>en cada viaje</small></span><span>☆ <b>Experiencias</b><small>memorables</small></span></div></section>
  <section className="section intro"><h2>Mucho más que transporte.</h2><div className="highlight-grid">{highlights.map(({Icon,title,text})=><article key={title}><Icon className="highlight-icon" strokeWidth={1.7} aria-hidden="true"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section trips" id="experiencias"><h2>Elige tu próxima experiencia.</h2><div className="trip-grid">{trips.map(({title,img,Icon},i)=><a href={whatsapp} className="trip" key={title} style={{backgroundImage:`linear-gradient(0deg, rgba(0,16,50,.88), rgba(0,16,50,.04) 75%), url(${img})`,backgroundPosition:`${i%4*11}% center`}}><Icon className="trip-icon" strokeWidth={1.7} aria-hidden="true"/><span>{title}</span></a>)}<article className="custom"><Users className="custom-icon" strokeWidth={1.7} aria-hidden="true"/><div><b>¿No encuentras tu destino?</b><p>Creamos experiencias a medida para ti y tu grupo.</p><a href={whatsapp}>Contáctanos →</a></div></article></div></section>
  <section className="section combo"><div className="interior"/><div className="combo-copy"><h2>Transporte + experiencia<br/>en una sola reserva.</h2><p>En destinos seleccionados puedes combinar tu traslado con entradas, actividades y experiencias únicas.</p></div><ul><li>✓ Traslado ida y regreso</li><li>✓ Coordinación del itinerario</li><li>✓ Opciones con entrada incluida</li><li>✓ Atención personalizada</li><li><a className="button light" href={whatsapp}>Consultar disponibilidad →</a></li></ul></section>
  <section className="section steps" id="reserva"><h2>Reserva en 3 pasos.</h2><div><article><i>1</i><b>Elige el destino</b><p>Explora nuestras opciones y selecciona tu experiencia favorita.</p></article><article><i>2</i><b>Cuéntanos cuántos viajan</b><p>Indícanos la fecha, pasajeros y cualquier requerimiento especial.</p></article><article><i>3</i><b>Confirma tu viaje</b><p>Te enviamos la propuesta y aseguramos tu reserva de forma rápida.</p></article></div></section>
  <section className="cta"><div><b>¿Dónde quieres ir?</b><span>Nosotros te llevamos.</span></div><a className="button light" href={whatsapp}>◉ Cotizar por WhatsApp →</a></section><footer><Brand/><span>© 2026 Rutas Confiables</span><span>Transporte de pasajeros · Tours · Experiencias</span><a href={whatsapp}>WhatsApp</a></footer>
  <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Cotizar viaje por WhatsApp al +56 9 3570 9244"><span className="whatsapp-icon">✆</span><span className="whatsapp-label"><small>¿Necesitas ayuda?</small><b>Escríbenos por WhatsApp</b></span></a>
</main>}
import { CableCar, Compass, Grape, Map, Mountain, MountainSnow, PawPrint, Snowflake, Users, Waves } from "lucide-react";
