import Link from "next/link";
import { Grape, Map, Mountain, MountainSnow, PawPrint, Users, Waves } from "lucide-react";
import { destinationSlug } from "@/lib/destinations";
import SiteFooter from "@/components/SiteFooter";
import MainMenu from "@/components/MainMenu";
const mountain="https://images.unsplash.com/photo-1704304343233-492236e5f34b?auto=format&fit=crop&w=1400&q=85",lion="https://images.unsplash.com/photo-1649724264150-50dbfdc606c5?auto=format&fit=crop&w=900&q=85",vineyard="https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=85",coast="https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=85";
const whatsapp="https://wa.me/56935709244?text=Hello%2C%20I%20would%20like%20a%20travel%20quote";
const highlights=[{Icon:MountainSnow,title:"Snow trips",text:"Enjoy Chile’s best ski resorts with comfortable and safe transportation."},{Icon:PawPrint,title:"Safari Park",text:"Live an unforgettable experience at Parque Safari Chile."},{Icon:Grape,title:"Wine routes",text:"Discover exclusive wineries with transfers and admission options."},{Icon:Mountain,title:"Portillo and Laguna del Inca",text:"Unique Andes scenery and the famous Laguna del Inca."},{Icon:Waves,title:"Coast and seaside",text:"Explore Chile’s best beaches and coastal cities."},{Icon:Map,title:"Cajón del Maipo",text:"Nature, adventure and relaxation just outside Santiago."}];
const trips=[{title:"Snow Park Farellones",img:"https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=900&q=85"},{title:"Valle Nevado",img:mountain},{title:"El Colorado",img:"https://images.unsplash.com/photo-1529669851596-ba9a5549af95?auto=format&fit=crop&w=900&q=85"},{title:"La Parva",img:"https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=900&q=85"},{title:"Portillo & Laguna del Inca",img:mountain},{title:"Cajón del Maipo",img:mountain},{title:"Embalse del Yeso",img:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b4178?auto=format&fit=crop&w=900&q=85"},{title:"Termas de Colina",img:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=85"},{title:"Viña Concha y Toro",img:vineyard},{title:"Viña Alyan",img:vineyard},{title:"Viña Vik",img:vineyard},{title:"Viña Santa Rita",img:vineyard},{title:"Viña del Mar & Valparaíso",img:coast},{title:"Algarrobo & Isla Negra",img:coast},{title:"Parque Safari",img:lion},{title:"City Tour Santiago",display:"Santiago City Tour",img:"/destinations/city-tour-santiago.jpg"},{title:"Tours personalizados",display:"Custom tours",img:mountain}];
function Brand(){return <><Link className="brand" href="/en"><img className="brand-logo" src="/favicon.png" alt="Rutas Confiables official logo"/><span className="header-brand-tagline">Passenger transportation<br/>and tours</span></Link><MainMenu locale="en"/></>}
export default function EnglishHome(){return <main>
<section className="hero" id="inicio"><nav><Brand/></nav><div className="hero-content"><p className="eyebrow">Private transportation · Santiago, Chile</p><h1>Your next journey<br/>starts here.</h1><p className="hero-copy">Discover snow, vineyards, coastline, mountains and unique Chilean experiences with comfortable, safe and personalized service.</p><div className="actions"><a className="button light" href="#experiencias">View destinations →</a><a className="button ghost" href={whatsapp}>Request a quote →</a></div></div><div className="trust"><span>◇ <b>Safe transportation</b><small>you can trust</small></span><span>♡ <b>Comfort</b><small>on every trip</small></span><span>☆ <b>Experiences</b><small>to remember</small></span></div></section>
<section className="section intro"><h2>Much more than transportation.</h2><div className="highlight-grid">{highlights.map(({Icon,title,text})=><article key={title}><Icon className="highlight-icon"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section trips" id="experiencias"><h2>Choose your next experience.</h2><div className="trip-grid">{trips.map(({title,display,img},i)=><Link href={`/en/destinos/${destinationSlug(title)}`} className="trip" key={title} style={{backgroundImage:`linear-gradient(0deg,rgba(0,16,50,.88),rgba(0,16,50,.04) 75%),url(${img})`,backgroundPosition:`${i%4*11}% center`}}><span>{display||title}</span></Link>)}<article className="custom"><Users className="custom-icon"/><div><b>Can’t find your destination?</b><p>We create tailored experiences for you and your group.</p><a href={whatsapp}>Contact us →</a></div></article></div></section>
<SiteFooter locale="en"/><a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Request a quote on WhatsApp"><img src="/whatsapp.svg" alt=""/></a>
</main>}
